name: CI

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 720
    continue-on-error: true

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!123" -Force)
    - name: Create Tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Download Timeout Script
      run: Invoke-WebRequest https://raw.githubusercontent.com/beatDat2/rdp1/main/timeout.ps1 -OutFile timeout.ps1
    - name: Keep Alive 1
      run: ./timeout.ps1
    - name: Keep Alive 2
      run: ./timeout.ps1
    - name: Keep Alive 3
      run: ./timeout.ps1
    - name: Keep Alive 4
      run: ./timeout.ps1
    - name: Keep Alive 5
      run: ./timeout.ps1
    - name: Keep Alive 6
      run: ./timeout.ps1
    - name: Keep Alive 7
      run: ./timeout.ps1
    - name: Keep Alive 8
      run: ./timeout.ps1
    - name: Keep Alive 9
      run: ./timeout.ps1
    - name: Keep Alive 10
      run: ./timeout.ps1
    - name: Keep Alive 11
      run: ./timeout.ps1


